//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliSummer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cena()
        {
            this.PedidoCena = new HashSet<PedidoCena>();
        }
    
        public int id_cena { get; set; }
        public string nombre_cena { get; set; }
        public int precio_cena { get; set; }
        public string descripcion_cena { get; set; }
        public string imagen_cena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoCena> PedidoCena { get; set; }
    }
}
