//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliSummer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliSummerDBEntities : DbContext
    {
        public DeliSummerDBEntities()
            : base("name=DeliSummerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almuerzo> Almuerzo { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Cena> Cena { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Desayuno> Desayuno { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<PedidoAlmuerzo> PedidoAlmuerzo { get; set; }
        public virtual DbSet<PedidoCena> PedidoCena { get; set; }
        public virtual DbSet<PedidoDesayuno> PedidoDesayuno { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
