//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliSummer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoCena
    {
        public int id_pedido_cena { get; set; }
        public int id_pedido { get; set; }
        public int id_cena { get; set; }
    
        public virtual Cena Cena { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
